//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspbet_mvc_beginner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_User
    {
        public int UserID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool IsAdmin { get; set; }
    }
}
